baseURL = "http://ryallaire.github.io/"
languageCode = "en-us"
title = "Ryan H. Allaire's Website"

theme = "academia-hugo"
# email = "test@example.com"
email_form = 0

## To get dark as the default add "dark" as a class to body. 
## Still haven't found the configuration place for this. 
